name: Build OnePlus 8T Clean Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: op8t

      # Встановлюємо Python 2, щоб старі скрипти OnePlus (на кшталт gcc-wrapper.py) не видавали помилок синтаксису
      - name: Set up Python 2.x
        uses: actions/setup-python@v5
        with:
          python-version: '2.x'

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex git libssl-dev libelf-dev clang lld llvm libncurses-dev gcc-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # 1. Створюємо конфіг саме для нашого OnePlus 8T (kebab)
          make O=out vendor/kebab_defconfig
          
          # 2. Фікс нових опцій ядра (запобігає зависанню збірки)
          make O=out ARCH=arm64 CC=clang olddefconfig
          
          # 3. Повна збірка ядра
          make -j$(nproc) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OnePlus-8T-Clean-Kernel
          path: |
            out/arch/arm64/boot/Image*
